###
POST http://localhost:3001/register
Content-Type: application/json

{
    "name":"CAO",
    "phone": "0332060870",
    "email": "cao@gmail.com",
    "password": "2",
    "age": 18,
    "gender": "orther",
    "address": "Tp.hcm"
}

###
GET http://localhost:3001/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDUxYjc2ZTlhOWIyOWUzZmZkZDE3NjIiLCJpYXQiOjE2ODMyODc1NzUsImV4cCI6MTY4MzI5NDc3NX0.189kEAvpy-0V4_cloFMcM_R_9sK0QVsIGjYRkE6PfxQ
Content-Type: application/json

{
    "systemS": "0"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
    "phone":"0332060875",
    "password": "2"
}

###
GET http://localhost:3001/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDRlY2NjODVmNDAyZjY0MzA5ZjYwNTciLCJpYXQiOjE2ODI4ODYxMDIsImV4cCI6MTY4Mjg5MzMwMn0.4RAHFX1IUYNF23NKA3XsR3THJV_LtKOcp6fXRWWSpNU


###
PUT http://localhost:3001/update-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDUxYjc2ZTlhOWIyOWUzZmZkZDE3NjIiLCJpYXQiOjE2ODMwNzY5ODMsImV4cCI6MTY4MzA4NDE4M30.eUhhDbX2Pu6yKnTWEPqsEbdKvikQmbgbUMQK8I1mj7I
Content-Type: application/json

{
    "name":"MINH CAO",
    "phone": "0332060875",
    "email": "minhminh@gmail.com",
    "age": 18,
    "gender": "orther",
    "address": "Tp.hcm"
}

###
DELETE http://localhost:3001/history/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDUxYjc2ZTlhOWIyOWUzZmZkZDE3NjIiLCJpYXQiOjE2ODMxNDUyNDEsImV4cCI6MTY4MzE1MjQ0MX0.rTZ1HKOrz2IFfakA9Z2Id16qY-hA01dWcAEFxxoNDXE
Content-Type: application/json

{
    "_id": "6451c5173248b4984b6464d9"
}

###
DELETE http://localhost:3001/history/delete-many
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDUxYjc2ZTlhOWIyOWUzZmZkZDE3NjIiLCJpYXQiOjE2ODMyODgzNTgsImV4cCI6MTY4MzI5NTU1OH0.0O1kpPji1Q-gs9buJagWRO5KRHp4oGm2g9s7YsZnSZ0
Content-Type: application/json

{
    "ids" : ["6454f0036fcb102fbd17a550", "6454f0076fcb102fbd17a552", "6454f0086fcb102fbd17a554"]
}

###
DELETE http://localhost:3001/history/delete-all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDUxYjc2ZTlhOWIyOWUzZmZkZDE3NjIiLCJpYXQiOjE2ODMyODc1NzUsImV4cCI6MTY4MzI5NDc3NX0.189kEAvpy-0V4_cloFMcM_R_9sK0QVsIGjYRkE6PfxQ
Content-Type: application/json

{}


